modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/KOTO28/smart-view/issues"
clientSideOnly=true
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/KOTO28/smart-view"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''
